### ISSUE TITLE
add run export?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/starlink-ast-feedstock#22]
Does this library need a run export consistent with its ABI compatibility?

**Comment by timj** [comment]
Unfortunately I don't really understand the question so I can't comment.

**Comment by beckermr** [comment]
The question is if you build a C or C++ code that dynamically links to this library, do you always have to link to the same version or can you link to different versions?

Each C/C++ package is different in this respect. 

The run exports are how conda handles this. If this package appears in the host section of a recipe and has a run export, then that run export (which is just a package spec with version constraint) automatically gets added to the run section. This ensures packages find the right versions of their deps at run time. 

For example, mpich is ABI compatible from version 3 to version 4. Thus if I build a package against mpich say 3.4.3, then I can link at runtime to any version in the range `>=3.4.3,<5`.

For starlink-ast, I am assuming it has a runtime constraint. What I don't know is what the range should be. In the absence of other information, an exact pin down to the patch version is safest.

**Comment by timj** [comment]
So this is really a statement about whether the project uses semantic versioning or not? If it's possible for a patch level to break the ABI or whether that only happens for a major release?

@dsberry, have you written down your approach to version numbers in AST?

**Comment by beckermr** [comment]
This is not about API compatibility. Consider a struct in C and suppose you insert a new member in the middle of the struct. 

This code is API compatible with the old version in the sense that if you have some project that uses it, that project will still compile against the new version.

However, it is not ABI compatible because in memory the structs have two different layouts. You cannot pass a struct allocated with the old layout to the new code since it will look in the wrong spots for its members.

**Comment by timj** [comment]
Right. What's the downside of making every release assume it is incompatible with a previous release? Is that how conda-forge assumes most things are?

**Comment by beckermr** [comment]
There is no big downside to assuming every release. This is what my PR in #24 does. I am happy to merge that. It does make solving environments a bit more tricky if you have two packages that depend on different versions, but we can fix that if needed by adding a global pin in conda-forge.
